#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -e
echo "========================================================"
echo "Running synth..."
yosys \
   -p "read -sv ${SCRIPT_DIR}/../ip/x_top/rtl/x_top.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/x_mem_2p_2048x2/rtl/x_mem_2p_2048x2.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/x_mem/rtl/x_mem.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/x_ctrl/rtl/x_ctrl.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/x_bin_to_therm/rtl/x_bin_to_therm.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/rtl-uart/rtl/x_uart_rx.sv" \
   -p "read -sv ${SCRIPT_DIR}/../ip/rtl-uart/rtl/x_uart_tx.sv" \
   -p "synth_ice40 -top x_top -json x_top.json" \
   > syn.log
cat syn.log | grep -A30 statistics
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json x_top.json --package ct256 --pcf ${SCRIPT_DIR}/x_top.pcf --asc x_top.asc > pnr.log
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k x_top.asc > time.log
cat time.log 
echo "========================================================"

